import { Product, AppConfig } from './types';

export const INITIAL_CONFIG: AppConfig = {
  company_1_name: "La Pallyra",
  company_1_slogan: "é um atelie de encadernação personalizada, onde o seu dia a dia está garantido com alta qualidade.",
  company_1_logo: "📓",
  company_2_name: "com amor, Guennita",
  company_2_slogan: "é um atelie de personalizados com cetim e cartonagem de luxo para momentos que tem que ser excepcionais.",
  company_2_logo: "👑",
  company_3_name: "Mimada Sim",
  company_3_slogan: "é um atelie que pra qualquer momento da sua vida você vai encontar uma lembrancinha/brinde personalizado que é do seu jeitinho.",
  company_3_logo: "💅",
  whatsapp_number: "+55 (44) 974002857",
  background_color: "#ffeef8",
  text_color: "#333333",
  checkout_banner: "",
  store_cnpj: "63.348.579/0001-06",
  store_qrcode: "https://via.placeholder.com/200?text=QR+Code",
  discord_webhook: "https://discord.com/api/webhooks/1499112536627351612/3an-navBtSEVdKXEIQ86Vi54VBmPjw6WxnoBimk_9cxVpKZDyT3DkIN0oMoLpI9gFdJS",
  telegram_bot_token: "8661786975:AAGazZQl2JOVfLF90m2BKu8y8N3UieBBSvA",
  telegram_chat_id: "8661786975",
  email_para_pedidos: ""
};

export const PRODUCTS: Product[] = [
  // La Pallyra
  { 
    id: "LP-4746", 
    code: "LP00001",
    company: "pallyra", 
    product_name: "Agenda 2024 Personalizada", 
    description: "Capa dura laminada com seu nome e frase favorita. 1 dia por página, miolo em 90g.", 
    retail_price: 85, 
    wholesale_price: 60, 
    wholesale_min_qty: 10, 
    original_price: 95, 
    current_price: 85, 
    image: "📓", 
    image_hover: "✍️", 
    category: "Papelaria", 
    subcategory: "Agendas",
    isVisible: true,
    isFeatured: true
  },
  { 
    id: "LP-1163", 
    code: "LP00002",
    company: "pallyra", 
    product_name: "Kit Brinde Corporativo", 
    description: "Caneca de porcelana + Bloco de notas + Caneta metal. Tudo com sua logo.", 
    retail_price: 120, 
    wholesale_price: 85, 
    wholesale_min_qty: 20, 
    original_price: 140, 
    current_price: 120, 
    image: "📦", 
    image_hover: "💼", 
    category: "Corporativo", 
    subcategory: "Kits",
    isVisible: true,
    isFeatured: false
  },
  { 
    id: "LP-1690", 
    code: "LP00003",
    company: "pallyra", 
    product_name: "Quadro Spotify Glass", 
    description: "Placa de acrílico com sua música e foto favorita. Escaneável pelo app.", 
    retail_price: 75, 
    wholesale_price: 55, 
    wholesale_min_qty: 5, 
    original_price: 85, 
    current_price: 75, 
    image: "🖼️", 
    image_hover: "🎵", 
    category: "Decoração", 
    subcategory: "Quadros",
    isVisible: true,
    isFeatured: true
  },
  { 
    id: "LP-4924", 
    code: "LP00004",
    company: "pallyra", 
    product_name: "Garrafa Térmica Gravada", 
    description: "Aço inox 500ml com gravação a laser permanente. Mantém 12h quente/24h frio.", 
    retail_price: 110, 
    wholesale_price: 75, 
    wholesale_min_qty: 15, 
    original_price: 130, 
    current_price: 110, 
    image: "🧴", 
    image_hover: "❄️", 
    category: "Utensílios", 
    subcategory: "Bebidas",
    isVisible: true,
    isFeatured: false
  },
  
  // com amor, Guennita
  { 
    id: "CG-0001", 
    code: "CG00001",
    company: "guennita", 
    product_name: "Box Luxury Rose Gold", 
    description: "Arranjo de flores preservadas em caixa aveludada. Dura até 2 anos.", 
    retail_price: 320, 
    wholesale_price: 240, 
    wholesale_min_qty: 3, 
    original_price: 380, 
    current_price: 320, 
    image: "🌹", 
    image_hover: "💖", 
    category: "Luxo", 
    subcategory: "Flores",
    isVisible: true,
    isFeatured: true
  },
  { 
    id: "CG-0002", 
    code: "CG00002",
    company: "guennita", 
    product_name: "Vela Crystal Gold", 
    description: "Cera vegetal premium com essência importada e detalhes em folha de ouro 24k.", 
    retail_price: 155, 
    wholesale_price: 110, 
    wholesale_min_qty: 6, 
    original_price: 180, 
    current_price: 155, 
    image: "🕯️", 
    image_hover: "✨", 
    category: "Home Decor", 
    subcategory: "Aromaterapia",
    isVisible: true,
    isFeatured: false
  },
  { 
    id: "CG-0003", 
    code: "CG00003",
    company: "guennita", 
    product_name: "Kit Lavabo Imperial", 
    description: "Sabonete líquido + Difusor de varetas em frascos de cristal lapidados à mão.", 
    retail_price: 285, 
    wholesale_price: 195, 
    wholesale_min_qty: 2, 
    original_price: 320, 
    current_price: 285, 
    image: "🧴", 
    image_hover: "💎", 
    category: "Home Decor", 
    subcategory: "Banho",
    isVisible: true,
    isFeatured: true
  },
  { 
    id: "CG-0004", 
    code: "CG00004",
    company: "guennita", 
    product_name: "Champagne Anniversary Board", 
    description: "Tábua de mármore personalizada com suporte para taças e detalhes em dourado.", 
    retail_price: 450, 
    wholesale_price: 320, 
    wholesale_min_qty: 2, 
    original_price: 520, 
    current_price: 450, 
    image: "🥂", 
    image_hover: "⭐", 
    category: "Luxo", 
    subcategory: "Gourmet",
    isVisible: true,
    isFeatured: false
  },
  
  // MIMADA SIM - Tudo sempre do meu jeitinho 
  { 
    id: "MS-0001", 
    code: "MS00001",
    company: "mimada", 
    product_name: "Bolsa Puffy Cloud", 
    description: "Bolsa super macia com alça ajustável. O must-have da estação.", 
    retail_price: 185, 
    wholesale_price: 130, 
    wholesale_min_qty: 4, 
    original_price: 220, 
    current_price: 185, 
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&q=80&w=800", 
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1605733513597-a8f8341084e6?auto=format&fit=crop&q=80&w=800"
    ],
    image_hover: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800", 
    category: "Fashion", 
    subcategory: "Bolsas",
    isVisible: true,
    isFeatured: true
  },
  { 
    id: "MS-0002", 
    code: "MS00002",
    company: "mimada", 
    product_name: "Kit Skincare Holograph", 
    description: "Contém rolo de quartzo rosa, espátula e faixa de cabelo em cetim.", 
    retail_price: 125, 
    wholesale_price: 85, 
    wholesale_min_qty: 8, 
    original_price: 150, 
    current_price: 125, 
    image: "💆", 
    image_hover: "✨", 
    category: "Beleza", 
    subcategory: "Pele",
    isVisible: true,
    isFeatured: false
  },
  { 
    id: "MS-0003", 
    code: "MS00003",
    company: "mimada", 
    product_name: "Óculos Dreamy Retro", 
    description: "Armação em acetato premium com lentes UV400. Design vintage moderno.", 
    retail_price: 145, 
    wholesale_price: 95, 
    wholesale_min_qty: 5, 
    original_price: 175, 
    current_price: 145, 
    image: "🕶️", 
    image_hover: "💖", 
    category: "Acessórios", 
    subcategory: "Óculos",
    isVisible: true,
    isFeatured: true
  },
  { 
    id: "MS-0004", 
    code: "MS00004",
    company: "mimada", 
    product_name: "Phone Strap Candy", 
    description: "Cordinha para celular feita à mão com miçangas premium e cristais.", 
    retail_price: 45, 
    wholesale_price: 25, 
    wholesale_min_qty: 15, 
    original_price: 60, 
    current_price: 45, 
    image: "🍭", 
    image_hover: "📱", 
    category: "Acessórios", 
    subcategory: "Celular",
    isVisible: true,
    isFeatured: false
  },
  { 
    id: "MS-0005", 
    code: "MS00005",
    company: "mimada", 
    product_name: "Combo Gloss Cherry", 
    description: "Kit com 3 glosses labiais com aroma de cereja e brilho intenso.", 
    retail_price: 95, 
    wholesale_price: 65, 
    wholesale_min_qty: 10, 
    original_price: 120, 
    current_price: 95, 
    image: "💄", 
    image_hover: "🍒", 
    category: "Beleza", 
    subcategory: "Lábios",
    isVisible: true,
    isFeatured: true
  }
];
